### ISSUE TITLE
Install and Configure Browserbase for Automated Development Preview

### ISSUE THREAD

**Issue by ahelme** [ahelme/alum-dash#11]
# Browserbase Automated Testing Setup for AlumDash Development 🤖

Perfect choice! Browserbase is excellent for automated testing during development. While it's not for deployment, it's absolutely perfect for automatically testing your preview deployments from Vercel, ensuring your UI changes work correctly across different browsers and scenarios.

## What Browserbase does for your development workflow

✅ **Automated UI testing** of your preview deployments  
✅ **Cross-browser testing** (Chrome, Firefox, Safari)  
✅ **Visual regression testing** with screenshots  
✅ **Performance monitoring** during development  
✅ **End-to-end user flow testing**  
✅ **Real browser automation** with session recording  

## Step 1: Get Your Browserbase Credentials

1. **Sign up at [[browserbase.com](https://www.browserbase.com/)](https://www.browserbase.com)**
2. **Create a new project** for AlumDash
3. **Get your API credentials** from the Dashboard Settings:
   - `BROWSERBASE_API_KEY`
   - `BROWSERBASE_PROJECT_ID`

## Step 2: Set Up Environment Variables

Add these to your project's `.env.local` file:

```bash
# Browserbase Configuration
BROWSERBASE_API_KEY=your_api_key_here
BROWSERBASE_PROJECT_ID=your_project_id_here

# OpenAI or Anthropic for AI-powered testing (optional)
OPENAI_API_KEY=your_openai_key_here
# OR
ANTHROPIC_API_KEY=your_anthropic_key_here
```

For Vite projects, use the `VITE_` prefix:

```bash
# For Vite React projects
VITE_BROWSERBASE_API_KEY=your_api_key_here
VITE_BROWSERBASE_PROJECT_ID=your_project_id_here
```

## Step 3: Install Dependencies

Install the Browserbase SDK and testing tools:

```bash
# Core Browserbase packages
npm install @browserbasehq/stagehand @browserbasehq/sdk

# Playwright for advanced automation
npm install --save-dev @playwright/test

# For AI-powered testing (optional)
npm install openai
# OR
npm install @anthropic-ai/sdk
```

### Basic Browserbase + Playwright Test Setup

Create `tests/browserbase-preview.test.js`:

```javascript
import { test, expect } from '@playwright/test';
import { Stagehand } from '@browserbasehq/stagehand';

// Configuration
const PREVIEW_URL = process.env.VERCEL_URL || 'http://localhost:5173';
const BROWSERBASE_API_KEY = process.env.BROWSERBASE_API_KEY;
const BROWSERBASE_PROJECT_ID = process.env.BROWSERBASE_PROJECT_ID;

test.describe('AlumDash Preview Testing', () => {
  let stagehand;

  test.beforeAll(async () => {
    // Initialize Stagehand with Browserbase
    stagehand = new Stagehand({
      env: 'BROWSERBASE',
      apiKey: BROWSERBASE_API_KEY,
      projectId: BROWSERBASE_PROJECT_ID,
      modelName: 'gpt-4o', // For AI-powered testing
      modelClientOptions: {
        apiKey: process.env.OPENAI_API_KEY,
      },
    });
    
    await stagehand.init();
  });

  test.afterAll(async () => {
    await stagehand?.close();
  });

  test('Homepage loads correctly', async () => {
    const page = stagehand.page;
    
    // Navigate to your preview deployment
    await page.goto(PREVIEW_URL);
    
    // Wait for the page to load
    await page.waitForLoadState('networkidle');
    
    // Take a screenshot for visual verification
    await page.screenshot({ 
      path: `test-results/homepage-${new Date().getTime()}.png`,
      fullPage: true 
    });
    
    // Test basic elements are present
    await expect(page.locator('h1')).toContainText('AlumDash');
    
    // Test navigation exists
    const navButtons = page.locator('[role="tablist"] button');
    await expect(navButtons).toHaveCount(6); // Dashboard, Alumni, Add, Import, Automation, History
  });

  test('Alumni data table loads and functions', async () => {
    const page = stagehand.page;
    
    await page.goto(`${PREVIEW_URL}`);
    
    // Click on Alumni tab using AI
    await page.act('click on the Alumni tab');
    
    // Wait for table to load
    await page.waitForSelector('table');
    
    // Take screenshot of alumni table
    await page.screenshot({ 
      path: `test-results/alumni-table-${new Date().getTime()}.png` 
    });
    
    // Test table has data
    const tableRows = page.locator('tbody tr');
    await expect(tableRows).toHaveCount.greaterThan(0);
    
    // Test search functionality works
    await page.fill('input[placeholder*="Search"]', 'Sarah');
    await page.waitForTimeout(1000); // Wait for search to filter
    
    // Verify search results
    const searchResults = page.locator('tbody tr');
    await expect(searchResults).toHaveCount.greaterThanOrEqual(1);
  });

  test('CSV Import interface works', async () => {
    const page = stagehand.page;
    
    await page.goto(PREVIEW_URL);
    
    // Navigate to CSV import using AI
    await page.act('click on Import CSV tab');
    
    // Verify upload area exists
    await expect(page.locator('[data-testid="file-upload-area"]')).toBeVisible();
    
    // Test template download
    await page.act('click download template button');
    
    // Take screenshot of import interface
    await page.screenshot({ 
      path: `test-results/csv-import-${new Date().getTime()}.png` 
    });
  });

  test('Automation Dashboard UI renders', async () => {
    const page = stagehand.page;
    
    await page.goto(PREVIEW_URL);
    
    // Navigate to automation dashboard
    await page.act('click on Automation tab');
    
    // Wait for dashboard to load
    await page.waitForSelector('[data-testid="automation-dashboard"]');
    
    // Test key components are present
    await expect(page.locator('text=Automation Dashboard')).toBeVisible();
    await expect(page.locator('text=System Status')).toBeVisible();
    
    // Take screenshot
    await page.screenshot({ 
      path: `test-results/automation-dashboard-${new Date().getTime()}.png` 
    });
  });
});
```

### AI-Powered End-to-End Test

Create `tests/ai-user-flows.test.js`:

```javascript
import { test } from '@playwright/test';
import { Stagehand } from '@browserbasehq/stagehand';

test('Complete user workflow with AI', async () => {
  const stagehand = new Stagehand({
    env: 'BROWSERBASE',
    apiKey: process.env.BROWSERBASE_API_KEY,
    projectId: process.env.BROWSERBASE_PROJECT_ID,
    modelName: 'gpt-4o',
    modelClientOptions: {
      apiKey: process.env.OPENAI_API_KEY,
    },
  });
  
  await stagehand.init();
  const page = stagehand.page;
  
  try {
    // Navigate to the app
    await page.goto(process.env.VERCEL_URL || 'http://localhost:5173');
    
    // AI-powered user simulation
    await page.act('Navigate to the Alumni section');
    await page.act('Search for an alumni named Sarah');
    await page.act('Click on the Add Alumni section');
    await page.act('Fill out the form with sample data but do not submit');
    await page.act('Navigate to the Import CSV section');
    await page.act('Click the download template button');
    
    // Extract information about the current state
    const appState = await page.extract({
      instruction: 'Describe the current state of the application',
      schema: {
        currentSection: 'string',
        visibleElements: 'array of strings',
        errors: 'array of strings'
      }
    });
    
    console.log('App State:', appState);
    
    // Take final screenshot
    await page.screenshot({ 
      path: `test-results/ai-workflow-complete-${new Date().getTime()}.png`,
      fullPage: true 
    });
    
  } finally {
    await stagehand.close();
  }
});
```

### GitHub Actions Integration

Create `.github/workflows/browserbase-testing.yml`:

```yaml
name: Automated Preview Testing

on:
  pull_request:
    types: [opened, synchronize]
  deployment_status:

jobs:
  browserbase-tests:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Browserbase tests on preview
        env:
          BROWSERBASE_API_KEY: ${{ secrets.BROWSERBASE_API_KEY }}
          BROWSERBASE_PROJECT_ID: ${{ secrets.BROWSERBASE_PROJECT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          VERCEL_URL: ${{ github.event.deployment_status.target_url }}
        run: |
          echo "Testing preview deployment: $VERCEL_URL"
          npx playwright test tests/browserbase-preview.test.js
          npx playwright test tests/ai-user-flows.test.js
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: browserbase-test-results
          path: test-results/
      
      - name: Comment PR with results
        if: always()
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🤖 **Browserbase automated testing complete!**
            
            Preview URL: ${{ github.event.deployment_status.target_url }}
            
            Tests run across multiple browsers with session recordings available in [Browserbase Dashboard](https://browserbase.com/dashboard).
            
            Check the Actions tab for detailed results and screenshots.
```

### Interactive Testing Script

Create `scripts/test-preview.js`:

```javascript
#!/usr/bin/env node

import { Stagehand } from '@browserbasehq/stagehand';
import { config } from 'dotenv';

config(); // Load .env variables

async function testCurrentBuild() {
  console.log('🚀 Starting Browserbase testing...');
  
  const stagehand = new Stagehand({
    env: 'BROWSERBASE',
    apiKey: process.env.BROWSERBASE_API_KEY,
    projectId: process.env.BROWSERBASE_PROJECT_ID,
    modelName: 'gpt-4o',
    modelClientOptions: {
      apiKey: process.env.OPENAI_API_KEY,
    },
  });
  
  await stagehand.init();
  const page = stagehand.page;
  
  try {
    // Test your local development server
    const testUrl = process.argv[2] || 'http://localhost:5173';
    console.log(`Testing: ${testUrl}`);
    
    await page.goto(testUrl);
    
    // Quick smoke test
    await page.act('Navigate through all main sections of the app');
    
    // Take screenshots of each section
    const sections = ['Dashboard', 'Alumni', 'Add Alumni', 'Import CSV', 'Automation'];
    
    for (const section of sections) {
      try {
        await page.act(`Click on ${section} tab`);
        await page.waitForTimeout(2000);
        await page.screenshot({ 
          path: `test-results/${section.toLowerCase().replace(' ', '-')}-${new Date().getTime()}.png` 
        });
        console.log(`✅ ${section} section tested`);
      } catch (error) {
        console.log(`❌ Error testing ${section}:`, error.message);
      }
    }
    
    console.log('🎉 Testing complete! Check test-results/ for screenshots.');
    console.log(`📊 View session recording at: https://browserbase.com/dashboard`);
    
  } catch (error) {
    console.error('❌ Test failed:', error);
  } finally {
    await stagehand.close();
  }
}

testCurrentBuild();
```

Make it executable and add to package.json:

```json
{
  "scripts": {
    "test:browserbase": "node scripts/test-preview.js",
    "test:preview": "node scripts/test-preview.js https://your-preview-url.vercel.app"
  }
}
```

### Visual Regression Testing

```javascript
// Add to your test files
test('Visual regression testing', async () => {
  const stagehand = new Stagehand({ /* config */ });
  await stagehand.init();
  const page = stagehand.page;
  
  await page.goto(PREVIEW_URL);
  
  // Take baseline screenshot
  await expect(page).toHaveScreenshot('homepage-baseline.png');
  
  // Test different screen sizes
  await page.setViewportSize({ width: 375, height: 667 }); // Mobile
  await expect(page).toHaveScreenshot('homepage-mobile.png');
  
  await page.setViewportSize({ width: 1920, height: 1080 }); // Desktop
  await expect(page).toHaveScreenshot('homepage-desktop.png');
  
  await stagehand.close();
});
```

### Performance Testing

```javascript
test('Performance monitoring', async () => {
  const stagehand = new Stagehand({ /* config */ });
  await stagehand.init();
  const page = stagehand.page;
  
  // Enable performance monitoring
  await page.route('**/*', route => {
    const request = route.request();
    console.log(`${request.method()} ${request.url()}`);
    route.continue();
  });
  
  const startTime = Date.now();
  await page.goto(PREVIEW_URL);
  await page.waitForLoadState('networkidle');
  const loadTime = Date.now() - startTime;
  
  console.log(`Page load time: ${loadTime}ms`);
  expect(loadTime).toBeLessThan(5000); // Should load within 5 seconds
  
  await stagehand.close();
});
```

### Daily Development Testing

```bash
# Test your local development server
npm run test:browserbase

# Test a specific preview URL
npm run test:preview https://alum-dash-pr-123.vercel.app

# Run full test suite
npx playwright test

# Run tests with live view (see browser in action)
npx playwright test --headed

# Generate test report
npx playwright show-report
```

### Setting Up Test Data

```javascript
// Create test-data/setup.js
export const createTestData = async (page) => {
  // Navigate to Add Alumni
  await page.act('Click on Add Alumni tab');
  
  // Fill in test alumni data
  const testAlumni = [
    { name: 'Test User 1', year: 2020, program: 'Film Production' },
    { name: 'Test User 2', year: 2021, program: 'Documentary' },
  ];
  
  for (const alumni of testAlumni) {
    await page.fill('[name="name"]', alumni.name);
    await page.fill('[name="graduation_year"]', alumni.year.toString());
    await page.selectOption('[name="degree_program"]', alumni.program);
    await page.click('button[type="submit"]');
    await page.waitForSelector('.success-message');
  }
};
```

## Benefits for Your Development Workflow

🎯 **Automated Quality Assurance**: Every preview deployment gets tested automatically  
🔍 **Visual Debugging**: Screenshots and session recordings for every test run  
🌐 **Cross-Browser Confidence**: Ensure your theming works in Chrome, Firefox, and Safari  
🚀 **Fast Feedback**: Know immediately if a UI change breaks functionality  
📱 **Responsive Testing**: Verify mobile and desktop layouts automatically  
🤖 **AI-Powered**: Let AI simulate real user interactions  

## Cost and Scaling

- **Free Tier**: 100 sessions/month (perfect for development)
- **Session Recording**: Every test is recorded for debugging
- **Parallel Testing**: Run multiple tests simultaneously
- **Integration Ready**: Works with your existing CI/CD pipeline

This setup gives you a professional-grade automated testing system that will catch UI issues before they reach users, while providing detailed debugging information through Browserbase's dashboard! 🚀
